spring:
  profiles:
    active: slack

  application:
    name:
      concert-reservation-api-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concert_reservation
    username: root
    password:
    hikari:
      maximum-pool-size: 20 # 기본값 : 10 (최대 20개의 쓰레드가 DB ConnectionPool을 가지고 동시에 처리하는 테스트 가능)
  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: create
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html




